export const CHECKUP_GOAL_DAY = 'CHECKUP_GOAL_DAY';

export const SETUP_GOAL_START = 'SETUP_GOAL_START';
export const SETUP_GOAL_SUCCESS = 'SETUP_GOAL_SUCCESS';
export const SETUP_GOAL_FAIL = 'SETUP_GOAL_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';