export const CHECKUP_GOAL_DAY = 'CHECKUP_GOAL_DAY';

export const SETUP_GOAL_START = 'SETUP_GOAL_START';
export const SETUP_GOAL_SUCCESS = 'SETUP_GOAL_SUCCESS';
export const SETUP_GOAL_FAIL = 'SETUP_GOAL_FAIL';
export const SETUP_GOAL_CANCEL = 'SETUP_GOAL_CANCEL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CREATE_USER_REPO = "CREATE_USER_REPO";
export const CREATE_USER_REPO_START = "CREATE_USER_REPO_START";
export const CREATE_USER_REPO_FAIL = "CREATE_USER_REPO_FAIL";
export const CREATE_USER_REPO_SUCCESS = "CREATE_USER_REPO_SUCCESS";

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_GOALS_START = 'FETCH_ORDERS_START';
export const FETCH_GOALS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_GOALS_FAIL = 'FETCH_ORDERS_FAIL';

export const EDIT_GOALS_LIST = 'EDIT_GOALS_LIST';

export const SELECT_GOAL_BY_ID = 'SELECT_GOAL_BY_ID';

export const FETCH_SELECTED_GOAL_SUCCESS = 'FETCH_SELECTED_GOAL_SUCCESS';
export const FETCH_SELECTED_GOAL_START = 'FETCH_SELECTED_GOAL_START';
export const FETCH_SELECTED_GOAL_FAIL = 'FETCH_SELECTED_GOAL_FAIL';

export const SETUP_GOAL_INDICATORS = 'SETUP_GOAL_INDICATORS';

export const UPDATE_GOAL_SUCCESS = 'UPDATE_GOAL_SUCCESS';
export const UPDATE_GOAL_START = 'UPDATE_GOAL_START';
export const UPDATE_GOAL_FAIL = 'UPDATE_GOAL_FAIL';

export const DELETE_GOAL_SUCCESS = 'DELETE_GOAL_SUCCESS';
export const DELETE_GOAL_START = 'DELETE_GOAL_START';
export const DELETE_GOAL_FAIL = 'UPDATE_GOAL_FAIL';


